export const Colors = {
    background: '#212121',
    background2: '#292929',
    orange: '#FF5122',
    darkOrange: '#EA3B13',
    text: '#ffffff',
    darkText: '#333',
    title: '#ed5d37',
    subTitle: '#dfdfdf',
    headerBtn: '#ffffff',
    musicBarBg: '#ed5d37',
    blue: '#4267B2',
    buttonColor: '#ffffff',
    buttonColorDisable: '#ccc',
    gray: '#cccccc',
    darkGray: '#a3a3a3',
    lightgray: '#eaeaea',
    red: '#FF003D',
  }
  